services:
  frontend:
    hostname: frontend
    build:
      context: .
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
